### ISSUE TITLE
Many calls to Log.Fatal

### ISSUE THREAD

**Issue by mm0** [cherryservers/cherrygo#1]
There is lots of usage of the Log.Fatal function which calls os.exit(1). This makes it difficult to test the code and prevents the errors being returned, for example:
```
  if err != nil {
    log.Fatal("Error in Delete: ", err)
  }
  return trans, resp, err
```
Nothing will ever be returned because the code exits before the return functions.

**Comment by ArturasRa** [comment]
Yes, indeed, you are right it will never return in those cases. I will review those parts and correct with next commit. Thanks for pointing.
