### ISSUE TITLE
CI/CD workflow with GitHub action

### ISSUE THREAD

**Issue by gianarb** [cherryservers/cherrygo#8]
Hello
I would like to share with you some of the tricks and tools I use to do CI but even better CD for libraries like this one. For example for testcontainers/testcontainers-go I use

https://github.com/apps/release-drafter

It helps me to do a release with one-click button. With an up to date changelog and a nice release page https://github.com/testcontainers/testcontainers-go/releases

I can help you to set it up

**Comment by zalmarge** [comment]
We've been running our CI/CD workflow for a couple of years now, so it's high time we express our gratitude. We've taken inspiration from your examples, @gianarb. Thanks a bunch!
